thisIsAReallyLongIdentifierButItShouldNotProduceAnError

thisIsAReallyLongIdentifierAndItShouldProduceAnErrorthisIsAReallyLongIdentifierAndItShouldProduceAnErrorthisIsAReallyLongIdentifierAndItShouldProduceAnErrorthisIsAReallyLongIdentifierAndItShouldProduceAnErrorthisIsAReallyLongIdentifierAndItShouldProduceAnErrorthisIsAReallyLongIdentifierAndItShouldProduceAnErrorthisIsAReallyLongIdentifierAndItShouldProduceAnErrorthisIsAReallyLongIdentifierAndItShouldProduceAnErrorthisIsAReallyLongIdentifierAndItShouldProduceAnErrorthisIsAReallyLongIdentifierAndItShouldProduceAnErrorthisIsAReallyLongIdentifierAndItShouldProduceAnErrorthisIsAReallyLongIdentifierAndItShouldProduceAnErrorthisIsAReallyLongIdentifierAndItShouldProduceAnErrorthisIsAReallyLongIdentifierAndItShouldProduceAnErrorthisIsAReallyLongIdentifierAndItShouldProduceAnErrorthisIsAReallyLongIdentifierAndItShouldProduceAnErrorthisIsAReallyLongIdentifierAndItShouldProduceAnErrorthisIsAReallyLongIdentifierAndItShouldProduceAnErrorthisIsAReallyLongIdentifierAndItShouldProduceAnErrorthisIsAReallyLongIdentifierAndItShou

#
@
$
`
"
\


/*      
        
        This is an unterminated comment
